In [2]:
import pandas as pd
iphone_df = pd.read_csv('C:/Users/gksal/Downloads/iphone.csv',index_col=0)
iphone_df

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [3]:
iphone_df.loc['iPhone 8','메모리']

'2GB'

In [4]:
iphone_df.loc['iPhone 8','메모리'] = '2.5GB'

In [5]:
iphone_df

                      출시일  디스플레이    메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7    2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5    3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2.5GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5    3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8    3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8    4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5    4GB  iOS 12.0     Yes

In [6]:
iphone_df.loc['iPhone 8']

출시일        2017-09-22
디스플레이             4.7
메모리             2.5GB
출시 버전        iOS 11.0
Face ID            No
Name: iPhone 8, dtype: object

In [7]:
iphone_df.loc['iPhone 8'] = ['2016-97-98','6.5','45','os33','Yes']

In [8]:
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16   4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16   5.5  3GB  iOS 10.0      No
iPhone 8       2016-97-98   6.5   45      os33     Yes
iPhone 8 Plus  2017-09-22   5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03   5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21   5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21   6.5  4GB  iOS 12.0     Yes

In [9]:
iphone_df['디스플레이'] = ['4,7in','43','34','354','345','67','45']

In [10]:
iphone_df['Face ID'] = 'YES'

In [11]:
iphone_df

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16  4,7in  2GB  iOS 10.0     YES
iPhone 7 Plus  2016-09-16     43  3GB  iOS 10.0     YES
iPhone 8       2016-97-98     34   45      os33     YES
iPhone 8 Plus  2017-09-22    354  3GB  iOS 11.0     YES
iPhone X       2017-11-03    345  3GB  iOS 11.1     YES
iPhone XS      2018-09-21     67  4GB  iOS 12.0     YES
iPhone XS Max  2018-09-21     45  4GB  iOS 12.0     YES

In [12]:
iphone_df[['디스플레이','Face ID']]

               디스플레이 Face ID
iPhone 7       4,7in     YES
iPhone 7 Plus     43     YES
iPhone 8          34     YES
iPhone 8 Plus    354     YES
iPhone X         345     YES
iPhone XS         67     YES
iPhone XS Max     45     YES

In [14]:
iphone_df[['디스플레이','Face ID']] = 'X'
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16     X  2GB  iOS 10.0       X
iPhone 7 Plus  2016-09-16     X  3GB  iOS 10.0       X
iPhone 8       2016-97-98     X   45      os33       X
iPhone 8 Plus  2017-09-22     X  3GB  iOS 11.0       X
iPhone X       2017-11-03     X  3GB  iOS 11.1       X
iPhone XS      2018-09-21     X  4GB  iOS 12.0       X
iPhone XS Max  2018-09-21     X  4GB  iOS 12.0       X

In [15]:
iphone_df.loc[['iPhone 7','iPhone 8']]

                 출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7  2016-09-16     X  2GB  iOS 10.0       X
iPhone 8  2016-97-98     X   45      os33       X

In [16]:
iphone_df.loc[['iPhone 7','iPhone 8']] ='o'

In [17]:
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7                o     o    o         o       o
iPhone 7 Plus  2016-09-16     X  3GB  iOS 10.0       X
iPhone 8                o     o    o         o       o
iPhone 8 Plus  2017-09-22     X  3GB  iOS 11.0       X
iPhone X       2017-11-03     X  3GB  iOS 11.1       X
iPhone XS      2018-09-21     X  4GB  iOS 12.0       X
iPhone XS Max  2018-09-21     X  4GB  iOS 12.0       X

In [18]:
iphone_df.loc['iPhone 7':'iPhone 8'] = '0'

In [27]:
iphone_df
iphone_df['디스플레이']=[5,5,6,6,3,2,8]

In [28]:
iphone_df['디스플레이']>5

iPhone 7         False
iPhone 7 Plus    False
iPhone 8          True
iPhone 8 Plus     True
iPhone X         False
iPhone XS        False
iPhone XS Max     True
Name: 디스플레이, dtype: bool

In [29]:
iphone_df.loc[iphone_df['디스플레이']>5]

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 8                0      6    0         0       0
iPhone 8 Plus  2017-09-22      6  3GB  iOS 11.0       X
iPhone XS Max  2018-09-21      8  4GB  iOS 12.0       X

In [30]:
iphone_df.loc[iphone_df['디스플레이']>5]='P'
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7                0     5    0         0       0
iPhone 7 Plus           0     5    0         0       0
iPhone 8                P     P    P         P       P
iPhone 8 Plus           P     P    P         P       P
iPhone X       2017-11-03     3  3GB  iOS 11.1       X
iPhone XS      2018-09-21     2  4GB  iOS 12.0       X
iPhone XS Max           P     P    P         P       P

In [31]:
iphone_df.iloc[[1,3],[1,4]]

              디스플레이 Face ID
iPhone 7 Plus     5       0
iPhone 8 Plus     P       P

In [6]:
iphone_df.iloc[[1,3],[1,4]] = 'v'

In [7]:
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16   4.7  2GB  iOS 10.0      No
iPhone 7 Plus           P     v    P         P       v
iPhone 8       2017-09-22   4.7  2GB  iOS 11.0      No
iPhone 8 Plus           P     v    P         P       v
iPhone X                P     P    P         P       P
iPhone XS               P     P    P         P       P
iPhone XS Max           P     P    P         P       P